import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Centralized utility for bundling, embedding, and shaping Malayalam fonts
/// (Noto Sans Malayalam) into PDF documents generated by package:pdf.
///
/// Ensures zero tofu/box characters and correct visual ordering for Malayalam
/// vowel signs across all platforms (Web, Windows, Android, iOS).
class PdfFontHelper {
  static pw.Font? _cachedMalayalamRegular;
  static pw.Font? _cachedMalayalamBold;
  static pw.Font? _cachedLatinRegular;
  static pw.Font? _cachedLatinBold;

  /// Loads and returns the embedded NotoSansMalayalam Regular font.
  static Future<pw.Font> getMalayalamRegular() async {
    if (_cachedMalayalamRegular != null) return _cachedMalayalamRegular!;
    final bytes = await _loadFontBytes('assets/fonts/NotoSansMalayalam-Regular.ttf');
    _cachedMalayalamRegular = pw.Font.ttf(ByteData.view(bytes.buffer));
    return _cachedMalayalamRegular!;
  }

  /// Loads and returns the embedded NotoSansMalayalam Bold font.
  static Future<pw.Font> getMalayalamBold() async {
    if (_cachedMalayalamBold != null) return _cachedMalayalamBold!;
    final bytes = await _loadFontBytes('assets/fonts/NotoSansMalayalam-Bold.ttf');
    _cachedMalayalamBold = pw.Font.ttf(ByteData.view(bytes.buffer));
    return _cachedMalayalamBold!;
  }

  static pw.Font getLatinRegular() {
    _cachedLatinRegular ??= pw.Font.helvetica();
    return _cachedLatinRegular!;
  }

  static pw.Font getLatinBold() {
    _cachedLatinBold ??= pw.Font.helveticaBold();
    return _cachedLatinBold!;
  }

  /// Builds a complete PDF ThemeData with embedded Malayalam fallback fonts.
  static Future<pw.ThemeData> getPdfTheme() async {
    final regular = await getMalayalamRegular();
    final bold = await getMalayalamBold();
    final latin = getLatinRegular();
    final latinBold = getLatinBold();

    return pw.ThemeData.withFont(
      base: latin,
      bold: latinBold,
      fontFallback: [regular, bold],
    );
  }

  /// Returns a TextStyle supporting both English and Malayalam.
  static Future<pw.TextStyle> textStyle({
    double fontSize = 10,
    bool isBold = false,
    PdfColor? color,
    pw.FontWeight? fontWeight,
  }) async {
    final regular = await getMalayalamRegular();
    final bold = await getMalayalamBold();
    final latin = (isBold || fontWeight == pw.FontWeight.bold) ? getLatinBold() : getLatinRegular();

    return pw.TextStyle(
      font: latin,
      fontFallback: isBold ? [bold, regular] : [regular, bold],
      fontSize: fontSize,
      fontWeight: isBold ? pw.FontWeight.bold : fontWeight,
      color: color,
    );
  }

  /// Reorders pre-base and two-part Malayalam vowels to visual order for PDF rendering,
  /// and normalizes chillaksharams to atomic Unicode codepoints (U+0D7A..U+0D7F).
  static String shape(String text) {
    if (text.isEmpty) return text;

    // 1. Normalize legacy chillu sequences
    var s = text
        .replaceAll('ര്\u200D', 'ർ')
        .replaceAll('ന്\u200D', 'ൻ')
        .replaceAll('ല്\u200D', 'ൽ')
        .replaceAll('ള്\u200D', 'ൾ')
        .replaceAll('ണ്\u200D', 'ൺ')
        .replaceAll('ക്\u200D', 'ൿ');

    final runes = s.runes.toList();
    final result = <int>[];

    bool isConsonant(int r) => (r >= 0x0D15 && r <= 0x0D3A);
    bool isVirama(int r) => r == 0x0D4D;

    int i = 0;
    while (i < runes.length) {
      if (isConsonant(runes[i])) {
        // Collect consonant cluster: C (+ virama + C)*
        int clusterStart = i;
        int clusterEnd = i + 1;
        while (clusterEnd < runes.length - 1 &&
            isVirama(runes[clusterEnd]) &&
            isConsonant(runes[clusterEnd + 1])) {
          clusterEnd += 2;
        }

        if (clusterEnd < runes.length) {
          int vowel = runes[clusterEnd];
          // Pre-base vowels: െ (0x0D46), േ (0x0D47), ൈ (0x0D48)
          if (vowel == 0x0D46 || vowel == 0x0D47 || vowel == 0x0D48) {
            result.add(vowel);
            for (int c = clusterStart; c < clusterEnd; c++) {
              result.add(runes[c]);
            }
            i = clusterEnd + 1;
            continue;
          }
          // Two-part vowel: ൊ (0x0D4A) -> െ (0x0D46) + Cluster + ാ (0x0D3E)
          else if (vowel == 0x0D4A) {
            result.add(0x0D46);
            for (int c = clusterStart; c < clusterEnd; c++) {
              result.add(runes[c]);
            }
            result.add(0x0D3E);
            i = clusterEnd + 1;
            continue;
          }
          // Two-part vowel: ോ (0x0D4B) -> േ (0x0D47) + Cluster + ാ (0x0D3E)
          else if (vowel == 0x0D4B) {
            result.add(0x0D47);
            for (int c = clusterStart; c < clusterEnd; c++) {
              result.add(runes[c]);
            }
            result.add(0x0D3E);
            i = clusterEnd + 1;
            continue;
          }
          // Two-part vowel: ൌ (0x0D4C) -> െ (0x0D46) + Cluster + ൗ (0x0D57)
          else if (vowel == 0x0D4C) {
            result.add(0x0D46);
            for (int c = clusterStart; c < clusterEnd; c++) {
              result.add(runes[c]);
            }
            result.add(0x0D57);
            i = clusterEnd + 1;
            continue;
          }
        }
      }

      result.add(runes[i]);
      i++;
    }

    return String.fromCharCodes(result);
  }

  static Future<Uint8List> _loadFontBytes(String path) async {
    try {
      final data = await rootBundle.load(path);
      return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    } catch (_) {
      // Fallback for tests or direct execution where rootBundle might not be bound to assets
      if (!kIsWeb) {
        final file = File(path);
        if (await file.exists()) {
          return await file.readAsBytes();
        }
      }
      rethrow;
    }
  }
}
